#!/usr/bin/env python
"""
A script to run a receipt analysis on all images in imgs/

@author: phdenzel

"""
import os
import sys
import csv
from receipt import Receipt

# collect image ids
image_files = [i for i in os.listdir(Receipt.imgd) if not i.startswith(".")]
image_names = [i.replace(".JPG", "").replace(".jpg", "") for i in image_files]
image_ids = [i.replace("IMG_", "").replace("img_", "") for i in image_names]

# run receipt analysis
try:
    auto = sys.argv[1]
except:
    auto = ""
if auto == "auto":
    isauto = True
    print("Auto-run on")
else:
    isauto = False
receipts = []
for _id in image_ids:
    receipts.append(Receipt(_id, auto=isauto))

# display and save information
info = ["Total", "Market", "Date", "Time"]
for r in receipts:
    r.print_properties()
    print
    info.append(r.market)
    info.append(r.total)
    info.append(r.date)
    info.append(r.time)

with open(Receipt.root+"out.csv", 'wb') as f:
    w = csv.writer(f, quoting=csv.QUOTE_ALL)
    w.writerow(info)
